#!/usr/bin/env python3
"""Generate src/ham.inc: the BBC port's Hamiltonian band rasterisers
(raster/shallow_12_hamiltonian-or.asm, shallow_23_hamiltonian-or.asm) as Z80,
block for block in the BBC's physical order (its fall-through edges stay
fall-throughs).  A block is one screen row: the row step, the run's plot(s)
with the byte crossings, the error update, and the carry-chosen branch to the
next run's block.  See raster.z80 pl_ham12/pl_ham23 for the entries."""
import os, re, sys
REF = "/tmp/doom_bbc_ref/raster"

def parse(fn, prefix):
    lines = open(os.path.join(REF, fn)).read().split("\n")
    blocks, cur, tramps = [], None, {}
    isblock = re.compile(r'^\.(%s)$' % prefix)
    for ln in lines:
        t = ln.strip()
        m = re.match(r'^\.([a-z0-9_]+)$', t)
        if m:
            name = m.group(1)
            if isblock.match(t):
                cur = {'name': name, 'ops': [], 'op': None, 'br': None, 'jmp': None}
                blocks.append(cur)
            elif name.startswith(('r_ftramp', 'r_btramp', 'l_ftramp', 'l_btramp', 'r23_tr', 'l23_tr')):
                cur = {'name': name, 'tramp': True, 'jmp': None}
                blocks.append(cur)
            elif cur is not None and not name.endswith(('_s',)) and not name.startswith(('r_skip', 'l_skip')):
                cur = None                      # row_handler etc.: out of the chain
            continue
        if cur is None:
            continue
        for mm in re.findall(r'LDA #&([0-9A-F]+)', t):
            cur.setdefault('ops', []).append(('plot', int(mm, 16)))
        if re.search(r'LDA scr:(ADC #[78]|ADC #8)', t):
            cur['ops'].append(('adj', +1))
        if re.search(r'LDA scr:SBC #[78]', t):
            cur['ops'].append(('adj', -1))
        if 'ADC delta1' in t: cur['op'] = 'add'
        if 'SBC delta2' in t: cur['op'] = 'sub'
        m = re.match(r'^(BCC|BCS) (\w+)', t)
        if m: cur['br'] = (m.group(1), m.group(2))
        m = re.match(r'^JMP (\w+)', t)
        if m: cur['jmp'] = m.group(1)
    for b in blocks:
        if b.get('tramp'): tramps[b['name']] = b['jmp']
    real = [b for b in blocks if not b.get('tramp')]
    def resolve(n):
        while n in tramps: n = tramps[n]
        return n
    for i, b in enumerate(real):
        b['brcc'], b['brto'] = b['br'][0], resolve(b['br'][1])
        b['fall'] = resolve(b['jmp']) if b['jmp'] else real[i + 1]['name']
        assert b['op'] in ('add', 'sub'), b
    return real

def emit(out, real, title):
    out.append("; --- %s ---" % title)
    names = [b['name'] for b in real]
    for i, b in enumerate(real):
        n = b['name']
        out.append("%s:" % n)
        out.append("                dec     iyl")
        out.append("                call    z,hm_cross")
        out.append("                dec     h")
        out.append("%s_s:" % n)
        for kind, v in b['ops']:
            if kind == 'plot':
                out.append("                ld      a,(hl)")
                out.append("                or      $%02X" % v)
                out.append("                ld      (hl),a")
            else:
                out.append("                inc     l" if v > 0 else "                dec     l")
        out.append("                ld      a,e")
        out.append("                add     a,d" if b['op'] == 'add' else "                sub     c")
        out.append("                ld      e,a")
        # 6502 carry after ADC = Z80 carry; after SBC the 6502 C = NOT borrow
        if b['op'] == 'add':
            cc = 'nc' if b['brcc'] == 'BCC' else 'c'
        else:
            cc = 'c' if b['brcc'] == 'BCC' else 'nc'
        out.append("                jp      %s,%s" % (cc, b['brto']))
        nxt = names[i + 1] if i + 1 < len(names) else None
        if b['fall'] != nxt:
            out.append("                jp      %s" % b['fall'])
    out.append("")

def table(out, name, entries):
    out.append("%s:" % name)
    for e in entries:
        out.append("                DW      %s" % e)

r12 = parse("shallow_12_hamiltonian-or.asm", r'[rl]_bit\d_p\d')
r23 = parse("shallow_23_hamiltonian-or.asm", r'[rl]23_\d_\d')
out = ["; Generated by tools/genham.py from the BBC port's Hamiltonian cores: do not edit.",
       "; The core runs with HL = the byte, IYL = the rows left in the cell, B = the",
       "; y-steps beyond it, E = e, D = delta1, C = delta2; a block is a row.",
       ""]
emit(out, r12, "the 1:2 band (dx/2 < dy <= dx): runs of 1 or 2")
emit(out, r23, "the 2:3 band (2dy < dx <= 3dy): runs of 2 or 3")
out.append("                ALIGN   256")
out.append("HAM_TAB:        ; the first block's plot by (x0 & 7) * 2 + leftward, both cores")
table(out, "HAM12_TAB", ["%s_bit%d_p1_s" % (d, p) for p in range(8) for d in "rl"])
table(out, "HAM23_TAB", ["%s23_%d_2_s" % (d, p) for p in range(8) for d in "rl"])
out.append("P23R:           DB      0,$C0,$60,$30,$18,$0C,$06,$03   ; the far pair, bits k-1..k")
out.append("P23L:           DB      $C0,$60,$30,$18,$0C,$06,$03,0   ; bits k..k+1")
open("src/ham.inc", "w").write("\n".join(out) + "\n")
print("ham.inc:", len(r12), "+", len(r23), "blocks")
