// The routines the profilers attribute time to.
exports.BUCKETS = new Set(["mul_u8","mul_s8_u8","mul_s16_u8","divs","fpmul8","mul_s8_s8",
  "rns_ahl","rns_hl","rns3_ahl","rns8_ahl","ev_at","linfn","pw","pw_diff","sp_alive",
  "sp_hasgap","sp_marksolid","sp_fuse","fu_ge","fu_verdict","ct_bounds","fu_lyext","fu_line","fu_out","fu_okeep","fu_orun","fu_above","sp_begin","sp_commit","pw_diff","pw_evd","sp_emit_range","sp_emit_range2","flush_edges","ct_span","ct_edge","queue_edge","sp_drawv","cross_col","cl_apply",
  "cl_at","cl_clampx","cl_clampy","to_view","rot_sin","rot_cos","recip","project_x",
  "project_y","view_setup","bbox_range","bb_edge","near_cross","vertex_get","vg_cold","vg_project","vx_slot","rs_near","near_cross_seg1","near_cross_seg2","rs_clip1","rs_clip2","rs_clipx","rs_do2","near_cross","sat_ahl",
  "point_on_side","render_seg","rs_visible","rs_havex","rs_bf_x0","rs_bf_y0","render_seg_body","rsb_p2","rsb_tighten","rsb_solid","walk","sp_emit","sp_commit","cmp_s16",
  "sincos_lookup","div16_8","dl_emit","dl_render","plot_line","raster_clear","sp_reset",
  "draw_clipped_line","dcl_cb_clip","dcl_vertical","dcl_vert_on","dcl_s16","dcl16_main","fw_walk_line","fw_walk_staged","fw_clip_span","fw_cb","fw_run_visible","fw_close_run","fused_apply_run","fw_split_r","fused_kill","fused_flat","fused_merge_range","fused_line","interp_store","umul_round_div","line_y8","cb_top_at","cb_bot_at","dcl_boundary_ix","s16_at","ms_u8","dcl_emit_segment","seg_zero_rec_solid","stage_line_ws","stage_top_ws","stage_bot_ws","stage_fwl_ws","fw_touch_close","fw_bval_top","fw_bval_bot","rsb_line","rsb_fused","rsb_stage","dcl_emit_open","dcl_close_open_nx","div8b","boundary_ix","line_y","interp_f","interp_c","interp_n","interp_s16","smul16","umul16","udiv32_16","sdiv_round","sdiv_floor","sdiv_ceil","udiv16_8","udiv16_16q8","cross_dir","sp_tighten","line_records","lr_onespan","lr_emit","lr_cross","tf_skip","tf_cand","tf_flush","sp_ends","sp_walk_begin","sp_advance","sp_relink","eo_from","cl_range","vspan_emit","ve_pair","rsb_vspans","rsb_line","rsb_bias","clamp_row","dc_draw_cs","ix_botline","se_mergeable",
  "ptoa","ptoa_memo","bb_corner_angle","bb_angtox","walk_child","walk_ss","emit_edge","mul_u8","plot_vert","addr_of","find_eye_height","update_world_pos","view_setup","vs_ptab","vs_pbtab","vs_patch5","vs_rebuild_b4","neg_pos","fterm","vs_fmul","vs_k32","vs_word","patch_sign","sincos_lookup","vs_origin",
  "bbox_visible","corner_phi_pp","corner_phi_pn","corner_phi_np","corner_phi_nn","lf_ns","lf_wide","bca_tail","zcf","zcf_dx","zcf_dy","zreload","zmemo_dx","zmemo_dy","walk_frame","walk_ss_segs","fe_descend","obj_subsector_stub","obj_subsector","obj_project","obj_draw_slot","obj_occluded","obj_probe","obj_hex","obj_s7","obj_grow","obj_lamp_xy","obj_box_y","obj_potion_xy","obj_helmet_xy","obj_vest_xy","obj_xladder","obj_yladder","obj_mirror","obj_ymirror","obj_rmul","obj_emit_direct"]);
